### ISSUE TITLE
shellydimmer2

### ISSUE THREAD

**Issue by goeran03** [Luligu/matterbridge-shelly#45]
I have the issue on shelly dimmer 2, that homekit shows "off" after a few seconds I turned the lamp on. In reality the lamp stays on. I have the latest firmware on the shelly 1.14.0.
Occationally, it is vice versa. It seems to be depending on what state of lamp I restarted the matterbridge.

Are there any settings I have to change for getting it working?

I have 2 of them, and both behave the same.

Thanks in advance
G.

**Comment by Luligu** [comment]
Hi,
that is typically the effect of wrong configuration of CoIoT settings for your device. Check please in the readme if you followed the procedure to configure it.
It happens when the controller sends the command, then the plugin executes it (you said the light is on), after the plugin didn't receive the update from the device so the controller reverts back to the before state.
Let me know if you need any more assistance.

**Comment by goeran03** [comment]
I was too quick. If I enable exposePowerMeter to eveHistory, obviously the update from device is missing again and the homekit button goes back after a few seconds (like described above)
Only with exposePowerMeter set to matter13 it works as expected.

**Comment by Luligu** [comment]
Hi, 
exposePowerMeter should not change anything. Did you save the settings in dimmer2 web page? And restart the dimmer2 from the web page?
Can you please enable all logger to debug and log tofile in Settings, restart and after a few minutes download matterbridge.log and send me?

**Comment by Luligu** [comment]
Btw I'm publishing a new version... 
I hope it is not cause you are in middle of the update.

**Comment by Luligu** [comment]
Did you solve?
